version: '3'
services:
  minio:
    image: 'bitnami/minio:latest'
    volumes:
      - minio_1_data_1:/data1
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
  image-hunter:
    build: ./image-hunter
    image: image-hunter
    ports:
      - '8080:8080'
    depends_on:
      - minio
  vectorizeme:
    build: ./vectorizeme
    image: vectorizeme
    ports:
      - '8000:8000'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.4.0
    container_name: kibana
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  qdrant:
    image: qdrant/qdrant
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    ports:
      - 6334:6334
    volumes:
      - qdrant-data:/qdrant/storage

volumes:
  minio_1_data_1:
    driver: local
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local
  qdrant-data:
    driver: local
